// VRM 애니메이션을 포함한 AI 응답을 위한 JSON 스키마
export const aiResponseSchema = {
  type: "object",
  properties: {
    textResponse: {
      type: "string",
      description: "AI의 텍스트 응답",
    },
    animation: {
      type: "object",
      properties: {
        expressions: {
          type: "object",
          properties: {
            happy: { type: ["number", "null"], minimum: 0, maximum: 1 },
            angry: { type: ["number", "null"], minimum: 0, maximum: 1 },
            sad: { type: ["number", "null"], minimum: 0, maximum: 1 },
            surprised: { type: ["number", "null"], minimum: 0, maximum: 1 },
            relaxed: { type: ["number", "null"], minimum: 0, maximum: 1 },
            neutral: { type: ["number", "null"], minimum: 0, maximum: 1 },
            joy: { type: ["number", "null"], minimum: 0, maximum: 1 },
            sorrow: { type: ["number", "null"], minimum: 0, maximum: 1 },
            fun: { type: ["number", "null"], minimum: 0, maximum: 1 },
            extra: { type: ["number", "null"], minimum: 0, maximum: 1 },
            blink: { type: ["number", "null"], minimum: 0, maximum: 1 },
            blinkLeft: { type: ["number", "null"], minimum: 0, maximum: 1 },
            blinkRight: { type: ["number", "null"], minimum: 0, maximum: 1 },
            lookUp: { type: ["number", "null"], minimum: 0, maximum: 1 },
            lookDown: { type: ["number", "null"], minimum: 0, maximum: 1 },
            lookLeft: { type: ["number", "null"], minimum: 0, maximum: 1 },
            lookRight: { type: ["number", "null"], minimum: 0, maximum: 1 },
            aa: { type: ["number", "null"], minimum: 0, maximum: 1 },
            ih: { type: ["number", "null"], minimum: 0, maximum: 1 },
            ou: { type: ["number", "null"], minimum: 0, maximum: 1 },
            ee: { type: ["number", "null"], minimum: 0, maximum: 1 },
            oh: { type: ["number", "null"], minimum: 0, maximum: 1 },
          },
          additionalProperties: false,
          required: [
            "happy",
            "angry",
            "sad",
            "surprised",
            "relaxed",
            "neutral",
            "joy",
            "sorrow",
            "fun",
            "extra",
            "blink",
            "blinkLeft",
            "blinkRight",
            "lookUp",
            "lookDown",
            "lookLeft",
            "lookRight",
            "aa",
            "ih",
            "ou",
            "ee",
            "oh",
          ],
        },
        lookAt: {
          type: "object",
          properties: {
            targetX: { type: ["number", "null"] },
            targetY: { type: ["number", "null"] },
            targetZ: { type: ["number", "null"] },
            intensity: { type: ["number", "null"], minimum: 0, maximum: 1 },
            yaw: { type: ["number", "null"], minimum: -45, maximum: 45 },
            pitch: { type: ["number", "null"], minimum: -30, maximum: 30 },
            smoothFactor: { type: ["number", "null"], minimum: 1, maximum: 20 },
            autoUpdate: { type: ["boolean", "null"] },
          },
          additionalProperties: false,
          required: [
            "targetX",
            "targetY",
            "targetZ",
            "intensity",
            "yaw",
            "pitch",
            "smoothFactor",
            "autoUpdate",
          ],
        },
        headGestures: {
          type: "object",
          properties: {
            nodIntensity: { type: ["number", "null"], minimum: 0, maximum: 1 },
            nodSpeed: { type: ["number", "null"], minimum: 0.5, maximum: 3.0 },
            nodRepeat: { type: ["number", "null"], minimum: 1, maximum: 5 },
            shakeIntensity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            shakeSpeed: {
              type: ["number", "null"],
              minimum: 0.5,
              maximum: 3.0,
            },
            shakeRepeat: { type: ["number", "null"], minimum: 1, maximum: 5 },
            tiltDirection: {
              type: ["number", "null"],
              minimum: -1,
              maximum: 1,
            },
            tiltIntensity: { type: ["number", "null"], minimum: 0, maximum: 1 },
            rotationX: { type: ["number", "null"], minimum: -30, maximum: 30 },
            rotationY: { type: ["number", "null"], minimum: -45, maximum: 45 },
            rotationZ: { type: ["number", "null"], minimum: -30, maximum: 30 },
          },
          additionalProperties: false,
          required: [
            "nodIntensity",
            "nodSpeed",
            "nodRepeat",
            "shakeIntensity",
            "shakeSpeed",
            "shakeRepeat",
            "tiltDirection",
            "tiltIntensity",
            "rotationX",
            "rotationY",
            "rotationZ",
          ],
        },
        handGestures: {
          type: "object",
          properties: {
            waveHand: {
              type: ["string", "null"],
              enum: ["none", "left", "right", "both", null],
            },
            waveIntensity: { type: ["number", "null"], minimum: 0, maximum: 1 },
            waveSpeed: { type: ["number", "null"], minimum: 0.5, maximum: 3.0 },
            pointHand: {
              type: ["string", "null"],
              enum: ["none", "left", "right", null],
            },
            pointDirection: {
              type: ["string", "null"],
              enum: ["forward", "up", "down", "left", "right", null],
            },
            pointIntensity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            thumbsUpHand: {
              type: ["string", "null"],
              enum: ["none", "left", "right", "both", null],
            },
            thumbsUpIntensity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            clapIntensity: { type: ["number", "null"], minimum: 0, maximum: 1 },
            clapSpeed: { type: ["number", "null"], minimum: 0.5, maximum: 3.0 },
            clapRepeat: { type: ["number", "null"], minimum: 1, maximum: 10 },
            crossArms: { type: ["number", "null"], minimum: 0, maximum: 1 },
            armSpread: { type: ["number", "null"], minimum: 0, maximum: 1 },
            armRaise: {
              type: ["string", "null"],
              enum: ["none", "left", "right", "both", null],
            },
            leftArmRotationX: { type: ["number", "null"], minimum: -180, maximum: 180 },
            leftArmRotationY: { type: ["number", "null"], minimum: -180, maximum: 180 },
            leftArmRotationZ: { type: ["number", "null"], minimum: -180, maximum: 180 },
            rightArmRotationX: { type: ["number", "null"], minimum: -180, maximum: 180 },
            rightArmRotationY: { type: ["number", "null"], minimum: -180, maximum: 180 },
            rightArmRotationZ: { type: ["number", "null"], minimum: -180, maximum: 180 },
            leftHandRotationX: { type: ["number", "null"], minimum: -90, maximum: 90 },
            leftHandRotationY: { type: ["number", "null"], minimum: -90, maximum: 90 },
            leftHandRotationZ: { type: ["number", "null"], minimum: -90, maximum: 90 },
            rightHandRotationX: { type: ["number", "null"], minimum: -90, maximum: 90 },
            rightHandRotationY: { type: ["number", "null"], minimum: -90, maximum: 90 },
            rightHandRotationZ: { type: ["number", "null"], minimum: -90, maximum: 90 },
          },
          additionalProperties: false,
          required: [
            "waveHand",
            "waveIntensity",
            "waveSpeed",
            "pointHand",
            "pointDirection",
            "pointIntensity",
            "thumbsUpHand",
            "thumbsUpIntensity",
            "clapIntensity",
            "clapSpeed",
            "clapRepeat",
            "crossArms",
            "armSpread",
            "armRaise",
            "leftArmRotationX",
            "leftArmRotationY",
            "leftArmRotationZ",
            "rightArmRotationX",
            "rightArmRotationY",
            "rightArmRotationZ",
            "leftHandRotationX",
            "leftHandRotationY",
            "leftHandRotationZ",
            "rightHandRotationX",
            "rightHandRotationY",
            "rightHandRotationZ",
          ],
        },
        bodyPosture: {
          type: "object",
          properties: {
            spineRotationX: {
              type: ["number", "null"],
              minimum: -30,
              maximum: 30,
            },
            spineRotationY: {
              type: ["number", "null"],
              minimum: -45,
              maximum: 45,
            },
            spineRotationZ: {
              type: ["number", "null"],
              minimum: -30,
              maximum: 30,
            },
            shoulderTension: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            shoulderShrug: { type: ["number", "null"], minimum: 0, maximum: 1 },
            leftShoulderHeight: { type: ["number", "null"], minimum: -0.5, maximum: 0.5 },
            rightShoulderHeight: { type: ["number", "null"], minimum: -0.5, maximum: 0.5 },
            confidence: { type: ["number", "null"], minimum: 0, maximum: 1 },
            openness: { type: ["number", "null"], minimum: 0, maximum: 1 },
            energy: { type: ["number", "null"], minimum: 0, maximum: 1 },
            weightShiftX: { type: ["number", "null"], minimum: -1, maximum: 1 },
            weightShiftZ: { type: ["number", "null"], minimum: -1, maximum: 1 },
            breathingIntensity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            breathingSpeed: {
              type: ["number", "null"],
              minimum: 0.5,
              maximum: 2.0,
            },
          },
          additionalProperties: false,
          required: [
            "spineRotationX",
            "spineRotationY",
            "spineRotationZ",
            "shoulderTension",
            "shoulderShrug",
            "leftShoulderHeight",
            "rightShoulderHeight",
            "confidence",
            "openness",
            "energy",
            "weightShiftX",
            "weightShiftZ",
            "breathingIntensity",
            "breathingSpeed",
          ],
        },
        idleMotion: {
          type: "object",
          properties: {
            autoBlinkEnabled: { type: ["boolean", "null"] },
            blinkFrequency: {
              type: ["number", "null"],
              minimum: 0.1,
              maximum: 5.0,
            },
            blinkIrregularity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            blinkDuration: {
              type: ["number", "null"],
              minimum: 0.1,
              maximum: 0.5,
            },
            headIdleEnabled: { type: ["boolean", "null"] },
            headIdleIntensity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            headIdleSpeed: {
              type: ["number", "null"],
              minimum: 0.1,
              maximum: 2.0,
            },
            bodySwayEnabled: { type: ["boolean", "null"] },
            bodySwayIntensity: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            bodySwaySpeed: {
              type: ["number", "null"],
              minimum: 0.1,
              maximum: 1.0,
            },
            autoBreathingEnabled: { type: ["boolean", "null"] },
            breathingDepth: {
              type: ["number", "null"],
              minimum: 0,
              maximum: 1,
            },
            breathingRate: {
              type: ["number", "null"],
              minimum: 0.5,
              maximum: 2.0,
            },
          },
          additionalProperties: false,
          required: [
            "autoBlinkEnabled",
            "blinkFrequency",
            "blinkIrregularity",
            "blinkDuration",
            "headIdleEnabled",
            "headIdleIntensity",
            "headIdleSpeed",
            "bodySwayEnabled",
            "bodySwayIntensity",
            "bodySwaySpeed",
            "autoBreathingEnabled",
            "breathingDepth",
            "breathingRate",
          ],
        },
        timing: {
          type: "object",
          properties: {
            duration: { type: ["number", "null"], minimum: 0.1, maximum: 10.0 },
            delay: { type: ["number", "null"], minimum: 0.0, maximum: 5.0 },
            easing: {
              type: ["string", "null"],
              enum: [
                "linear",
                "ease-in",
                "ease-out",
                "ease-in-out",
                "bounce",
                "elastic",
                null,
              ],
            },
            loop: { type: ["boolean", "null"] },
            repeat: { type: ["number", "null"], minimum: 1, maximum: 10 },
            yoyo: { type: ["boolean", "null"] },
            autoRevert: { type: ["boolean", "null"] },
            revertDelay: {
              type: ["number", "null"],
              minimum: 0.0,
              maximum: 5.0,
            },
            revertDuration: {
              type: ["number", "null"],
              minimum: 0.1,
              maximum: 3.0,
            },
          },
          additionalProperties: false,
          required: [
            "duration",
            "delay",
            "easing",
            "loop",
            "repeat",
            "yoyo",
            "autoRevert",
            "revertDelay",
            "revertDuration",
          ],
        },
      },
      additionalProperties: false,
      required: [
        "expressions",
        "lookAt",
        "headGestures",
        "handGestures",
        "bodyPosture",
        "idleMotion",
        "timing",
      ],
    },
    priority: {
      type: "string",
      enum: ["low", "medium", "high"],
      description: "애니메이션 우선순위",
    },
  },
  additionalProperties: false,
  required: ["textResponse", "animation", "priority"],
} as const;
